// Code generated by go-swagger; DO NOT EDIT.

// Package restapi k8-ipam Agent API
//
//	k8-ipam Agent
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: v1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
