apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  {{ .Values.ipamwrapperAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipamwrapper.ipamwrapperAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ipamwrapper.ipamwrapperAgent.selectorLabels" . | nindent 6 }}
  {{- with .Values.ipamwrapperAgent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if or .Values.ipamwrapperAgent.podAnnotations .Values.global.commonAnnotations }}
      annotations:
        {{- if .Values.global.commonAnnotations }}
          {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
          {{- end }}
          {{- if .Values.ipamwrapperAgent.podAnnotations }}
          {{- include "tplvalues.render" ( dict "value" .Values.ipamwrapperAgent.podAnnotations "context" $ ) | nindent 8 }}
          {{- end }}
          {{- end }}
      labels:
        {{- include "ipamwrapper.ipamwrapperAgent.selectorLabels" . | nindent 8 }}
          {{- if .Values.global.commonLabels }}
          {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
          {{- end }}
          {{- if .Values.ipamwrapperAgent.podLabels }}
          {{- include "tplvalues.render" ( dict "value" .Values.ipamwrapperAgent.podLabels "context" $ ) | nindent 8 }}
          {{- end }}
    spec:
      {{- if .Values.ipamwrapperAgent.image.imagePullSecrets }}
      imagePullSecrets:
      {{- with .Values.ipamwrapperAgent.image.imagePullSecrets }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.ipamwrapperAgent.name | trunc 63 | trimSuffix "-" }}
      priorityClassName: {{ default "system-node-critical" .Values.ipamwrapperAgent.priorityClassName }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      {{- with .Values.ipamwrapperAgent.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ipamwrapperAgent.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ipamwrapperAgent.affinity }}
      affinity:
      {{- include "tplvalues.render" (dict "value" .Values.ipamwrapperAgent.affinity "context" $) | nindent 6 }}
      {{- else }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              # Compatible with Kubernetes 1.12.x and 1.13.x
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
      {{- end }}
      containers:
      - name: {{ .Values.ipamwrapperAgent.name | trunc 63 | trimSuffix "-" }}
        image: {{ include "ipamwrapper.ipamwrapperAgent.image" . | quote }}
        imagePullPolicy: {{ .Values.ipamwrapperAgent.image.pullPolicy }}
        command:
        - {{ .Values.ipamwrapperAgent.binName }}
        args:
        - --config-path=/tmp/ipamwrapper/config-map/conf.yml
        {{- with .Values.ipamwrapperAgent.extraArgs }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
        {{- if .Values.ipamwrapperAgent.prometheus.enabled }}
        ports:
        - name: metrics
          containerPort: {{ .Values.ipamwrapperAgent.prometheus.port }}
          protocol: TCP
        {{- end }}
        {{- with .Values.ipamwrapperAgent.resources }}
        resources:
        {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        lifecycle:
          postStart:
            # Move an eventual old existing binary out of the way, we can't delete it as it might be in use right now
            exec:
              command: [ "/bin/sh", "-c", "if [ -f '/host/opt/cni/bin/ipamwrapper' ];then rm -f /host/opt/cni/bin/ipamwrapper.old ; mv /host/opt/cni/bin/ipamwrapper /host/opt/cni/bin/ipamwrapper.old ; fi; cp /usr/bin/ipamwrapper  /host/opt/cni/bin/ipamwrapper ; cp /usr/bin/router  /host/opt/cni/bin/router ; rm -f /host/opt/cni/bin/ipamwrapper.old &>/dev/null || true " ]
          preStop:
            exec:
              command:
                - {{ .Values.ipamwrapperAgent.binName }}
                - shutdown
        env:
        - name: IPAMWRAPPER_LOG_LEVEL
          value: {{ .Values.ipamwrapperAgent.debug.logLevel | quote }}
        - name: IPAMWRAPPER_ENABLED_METRIC
          value: {{ .Values.ipamwrapperAgent.prometheus.enabled | quote }}
        - name: IPAMWRAPPER_METRIC_HTTP_PORT
          value: {{ .Values.ipamwrapperAgent.prometheus.port | quote }}
        - name: IPAMWRAPPER_HEALTH_PORT
          value: {{ .Values.ipamwrapperAgent.httpPort | quote }}
        - name: IPAMWRAPPER_GOPS_LISTEN_PORT
          value: {{ .Values.ipamwrapperAgent.debug.gopsPort | quote }}
        {{- with .Values.ipamwrapperAgent.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ipamwrapperAgent.securityContext }}
        securityContext:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config-path
          mountPath: /tmp/ipamwrapper/config-map
          readOnly: true
        - name: cni-bin-path
          mountPath: /host/{{ .Values.global.ipamBinHostPath }}
        - name: ipam-unix-socket-dir
          mountPath: {{ dir .Values.global.ipamUNIXSocketHostPath }}
        {{- if .Values.ipamwrapperAgent.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.ipamwrapperAgent.extraVolumeMounts "context" $ ) | nindent 8 }}
        {{- end }}
      volumes:
        # To read the configuration from the config map
      - name: config-path
        configMap:
          defaultMode: 0400
          name: {{ .Values.global.configName }}
      - name: cni-bin-path
        hostPath:
          path:  {{ .Values.global.ipamBinHostPath }}
          type: DirectoryOrCreate
        # To create unix socket dir in the host
      - name: ipam-unix-socket-dir
        hostPath:
          path: {{ dir .Values.global.ipamUNIXSocketHostPath }}
          type: DirectoryOrCreate
      {{- if .Values.ipamwrapperAgent.extraVolumeMounts }}
      {{- include "tplvalues.render" ( dict "value" .Values.ipamwrapperAgent.extraVolumeMounts "context" $ ) | nindent 6 }}
      {{- end }}
