{{- if or .Values.ipam.enableIPv4 .Values.ipam.enableIPv6 -}}
{{- if or .Values.clusterDefaultPool.installIPv4IPPool .Values.clusterDefaultPool.installIPv6IPPool .Values.coordinator.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.ipamwrapperInit.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ipamwrapper.ipamwrapperInit.selectorLabels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.ipamwrapperInit.podLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.ipamwrapperInit.podLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.ipamwrapperInit.podAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.ipamwrapperInit.podAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ipamwrapperInit.image.imagePullSecrets }}
  imagePullSecrets:
  {{- with .Values.ipamwrapperInit.image.imagePullSecrets }}
  {{- toYaml . | trim | nindent 2 }}
  {{- end }}
  {{- end }}
  serviceAccountName: {{ .Values.ipamwrapperInit.name | trunc 63 | trimSuffix "-" }}
  priorityClassName: {{ default "system-node-critical" .Values.ipamwrapperInit.priorityClassName }}
  {{- if .Values.ipamwrapperInit.hostnetwork }}
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  {{- else }}
  hostNetwork: false
  dnsPolicy: ClusterFirst
  {{- end }}
  restartPolicy: Never
  {{- with .Values.ipamwrapperInit.tolerations }}
  tolerations:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.ipamwrapperInit.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ipamwrapperInit.affinity }}
  affinity:
  {{- include "tplvalues.render" (dict "value" .Values.ipamwrapperInit.affinity "context" $) | nindent 2 }}
  {{- end }}
  containers:
  - name: {{ .Values.ipamwrapperInit.name | trunc 63 | trimSuffix "-" }}
    image: {{ include "ipamwrapper.ipamwrapperInit.image" . | quote }}
    imagePullPolicy: {{ .Values.ipamwrapperInit.image.pullPolicy }}
    command:
      - {{ .Values.ipamwrapperInit.binName }}
    {{- with .Values.ipamwrapperInit.extraArgs }}
    args:
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.ipamwrapperInit.resources }}
    resources:
    {{- toYaml . | trim | nindent 6 }}
    {{- end }}
    {{- with .Values.ipamwrapperInit.securityContext }}
    securityContext:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    env:
    {{- with .Values.ipamwrapperInit.extraEnv }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    - name: IPAMWRAPPER_NAMESPACE
      value: {{ .Release.Namespace | quote }}
    - name: IPAMWRAPPER_CONTROLLER_NAME
      value: {{ .Values.ipamwrapperController.name | trunc 63 | trimSuffix "-" }}
    {{- if .Values.coordinator.enabled }}
    - name: IPAMWRAPPER_INIT_DEFAULT_COORDINATOR_NAME
      value: {{ .Values.coordinator.name | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_COORDINATOR_MODE
      value: {{ .Values.coordinator.mode | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_COORDINATOR_POD_CIDR_TYPE
      value: {{ .Values.coordinator.podCIDRType | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_COORDINATOR_DETECT_GATEWAY
      value: {{ .Values.coordinator.detectGateway | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_COORDINATOR_DETECT_IP_CONFLICT
      value: {{ .Values.coordinator.detectIPConflict | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_COORDINATOR_TUNE_POD_ROUTES
      value: {{ .Values.coordinator.tunePodRoutes | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_COORDINATOR_HIJACK_CIDR
      value: {{ toJson .Values.coordinator.hijackCIDR | quote }}
    {{- end }}
    {{- if and .Values.clusterDefaultPool.installIPv4IPPool .Values.ipam.enableIPv4 }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV4_IPPOOL_NAME
      value: {{ .Values.clusterDefaultPool.ipv4IPPoolName | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV4_IPPOOL_SUBNET
      value: {{ .Values.clusterDefaultPool.ipv4Subnet | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV4_IPPOOL_IPRANGES
      value: {{ toJson .Values.clusterDefaultPool.ipv4IPRanges | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV4_IPPOOL_GATEWAY
      value: {{ .Values.clusterDefaultPool.ipv4Gateway | quote }}
    {{- if .Values.ipam.enableSpiderSubnet }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV4_SUBNET_NAME
      value: {{ .Values.clusterDefaultPool.ipv4SubnetName | quote }}
    {{- end }}
    {{- end }}
    {{- if and .Values.clusterDefaultPool.installIPv6IPPool .Values.ipam.enableIPv6 }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV6_IPPOOL_NAME
      value: {{ .Values.clusterDefaultPool.ipv6IPPoolName | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV6_IPPOOL_SUBNET
      value: {{ .Values.clusterDefaultPool.ipv6Subnet | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV6_IPPOOL_IPRANGES
      value: {{ toJson .Values.clusterDefaultPool.ipv6IPRanges | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV6_IPPOOL_GATEWAY
      value: {{ .Values.clusterDefaultPool.ipv6Gateway | quote }}
    {{- if .Values.ipam.enableSpiderSubnet }}
    - name: IPAMWRAPPER_INIT_DEFAULT_IPV6_SUBNET_NAME
      value: {{ .Values.clusterDefaultPool.ipv6SubnetName | quote }}
    {{- end }}
    {{- end }}
    - name: IPAMWRAPPER_INIT_ENABLE_MULTUS_CONFIG
      value: {{ .Values.multus.enableMultusConfig | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_CNI_NAME
      value: {{ .Values.multus.multusCNI.defaultCniCRName | quote }}
    - name: IPAMWRAPPER_INIT_DEFAULT_CNI_NAMESPACE
      value: {{ .Release.Namespace | quote }}
    {{- if eq .Values.multus.multusCNI.defaultCniCRName "" }}
    - name: IPAMWRAPPER_INIT_DEFAULT_CNI_DIR
      value: {{ .Values.global.cniConfHostPath | quote }}
    volumeMounts:
      - name: cni
        mountPath: {{ .Values.global.cniConfHostPath }}
  volumes:
    - name: cni
      hostPath:
        path: {{ .Values.global.cniConfHostPath }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ipamwrapperInit.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipamwrapper.ipamwrapperInit.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.ipamwrapperInit.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.ipamwrapperInit.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.ipamwrapperInit.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}