// Code generated by go-swagger; DO NOT EDIT.

package ipamwrapper_agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Inspur-Data/ipamwrapper/api/v1/models"
)

// NewPostIpamParams creates a new PostIpamParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostIpamParams() *PostIpamParams {
	return &PostIpamParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostIpamParamsWithTimeout creates a new PostIpamParams object
// with the ability to set a timeout on a request.
func NewPostIpamParamsWithTimeout(timeout time.Duration) *PostIpamParams {
	return &PostIpamParams{
		timeout: timeout,
	}
}

// NewPostIpamParamsWithContext creates a new PostIpamParams object
// with the ability to set a context for a request.
func NewPostIpamParamsWithContext(ctx context.Context) *PostIpamParams {
	return &PostIpamParams{
		Context: ctx,
	}
}

// NewPostIpamParamsWithHTTPClient creates a new PostIpamParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostIpamParamsWithHTTPClient(client *http.Client) *PostIpamParams {
	return &PostIpamParams{
		HTTPClient: client,
	}
}

/*
PostIpamParams contains all the parameters to send to the API endpoint

	for the post ipam operation.

	Typically these are written to a http.Request.
*/
type PostIpamParams struct {

	// IpamAllocArgs.
	IpamAllocArgs *models.IpamAllocArgs

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post ipam params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostIpamParams) WithDefaults() *PostIpamParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post ipam params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostIpamParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post ipam params
func (o *PostIpamParams) WithTimeout(timeout time.Duration) *PostIpamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post ipam params
func (o *PostIpamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post ipam params
func (o *PostIpamParams) WithContext(ctx context.Context) *PostIpamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post ipam params
func (o *PostIpamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post ipam params
func (o *PostIpamParams) WithHTTPClient(client *http.Client) *PostIpamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post ipam params
func (o *PostIpamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIpamAllocArgs adds the ipamAllocArgs to the post ipam params
func (o *PostIpamParams) WithIpamAllocArgs(ipamAllocArgs *models.IpamAllocArgs) *PostIpamParams {
	o.SetIpamAllocArgs(ipamAllocArgs)
	return o
}

// SetIpamAllocArgs adds the ipamAllocArgs to the post ipam params
func (o *PostIpamParams) SetIpamAllocArgs(ipamAllocArgs *models.IpamAllocArgs) {
	o.IpamAllocArgs = ipamAllocArgs
}

// WriteToRequest writes these params to a swagger request
func (o *PostIpamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.IpamAllocArgs != nil {
		if err := r.SetBodyParam(o.IpamAllocArgs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
