apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  conf.yml: |
    ipamUnixSocketPath: {{ .Values.global.ipamUNIXSocketHostPath }}
    networkMode: {{ .Values.feature.networkMode }}
    enableIPv4: {{ .Values.feature.enableIPv4 }}
    enableIPv6: {{ .Values.feature.enableIPv6 }}
    enableStatefulSet: {{ .Values.feature.enableStatefulSet }}
    enableSubnet: {{ .Values.feature.enableSubnet }}
