// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RouterRule Get Router Rule
// swagger:model RouterRule
type RouterRule struct {
	// v4dst
	V4Dst string `json:"v4dst,omitempty"`

	// v6dst
	V6Dst string `json:"v6dst,omitempty"`

	// v4gw
	V4Gw string `json:"v4gw,omitempty"`

	// v6gw
	V6Gw string `json:"v6gw,omitempty"`

	// dynamicRouterGW
	DynamicRouterGW bool `json:"dynamicRouterGW,omitempty"`
}

// Validate validates this router rule
func (m *RouterRule) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this router rule based on context it is used
func (m *RouterRule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RouterRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RouterRule) UnmarshalBinary(b []byte) error {
	var res RouterRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
