apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tomcat-sts
  namespace: kube-system
spec:
  serviceName: test
  replicas: 1
  selector:
    matchLabels:
      app: mytomcat
  template:
    metadata:
      creationTimestamp: null
      annotations:
        v1.multus-cni.io/default-network: kube-system/ipamwrapper1
        ipam.inspur.io/ippool: |-
          {
            "ipv4": ["ippool-test"]
          }

      labels:
        app: mytomcat
    spec:
      nodeSelector: 
        kubernetes.io/hostname: node2
      containers:
      - image: 100.2.216.244:30012/library/tomcat:8.5.39
        imagePullPolicy: IfNotPresent
        name: mytomcat1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            mellanox.com/cx6_sriov_netdev: "1"
          requests:
            mellanox.com/cx6_sriov_netdev: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
