apiVersion: inspuripam.inspur.com/v1
kind: IPPool
metadata:
  labels:
    app.kubernetes.io/name: ippool
    app.kubernetes.io/instance: ippool-sample
    app.kubernetes.io/part-of: ipam
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ipam
    default: "true"
  name: ippool-sample
spec:
  default: true
  # TODO(user): Add fields here
  cidr: 1.2.3.4/24
  ipVersion: 4
  ips:
   - 1.2.3.4-1.2.3.89
