// Code generated by go-swagger; DO NOT EDIT.

package health_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHealthyParams creates a new GetHealthyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHealthyParams() *GetHealthyParams {
	return &GetHealthyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHealthyParamsWithTimeout creates a new GetHealthyParams object
// with the ability to set a timeout on a request.
func NewGetHealthyParamsWithTimeout(timeout time.Duration) *GetHealthyParams {
	return &GetHealthyParams{
		timeout: timeout,
	}
}

// NewGetHealthyParamsWithContext creates a new GetHealthyParams object
// with the ability to set a context for a request.
func NewGetHealthyParamsWithContext(ctx context.Context) *GetHealthyParams {
	return &GetHealthyParams{
		Context: ctx,
	}
}

// NewGetHealthyParamsWithHTTPClient creates a new GetHealthyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHealthyParamsWithHTTPClient(client *http.Client) *GetHealthyParams {
	return &GetHealthyParams{
		HTTPClient: client,
	}
}

/*
GetHealthyParams contains all the parameters to send to the API endpoint

	for the get healthy operation.

	Typically these are written to a http.Request.
*/
type GetHealthyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get healthy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthyParams) WithDefaults() *GetHealthyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get healthy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get healthy params
func (o *GetHealthyParams) WithTimeout(timeout time.Duration) *GetHealthyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get healthy params
func (o *GetHealthyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get healthy params
func (o *GetHealthyParams) WithContext(ctx context.Context) *GetHealthyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get healthy params
func (o *GetHealthyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get healthy params
func (o *GetHealthyParams) WithHTTPClient(client *http.Client) *GetHealthyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get healthy params
func (o *GetHealthyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHealthyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
