apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    inspur/networkName: ipamwrapper
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/cx6_sriov_netdev
  name: ipamwrapper1
  namespace: kube-system
spec:
  config: '{ "name":"sriov-network", "cniVersion":"0.3.1","plugins":[ {"type":"sriov","ipam":{"type":"ipamwrapper-cni"}}]}'
