name: Build x86 Image

on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - '**.md'
    
  push:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - '**.md'

jobs:
  build-and-push-imag-k8-ipam:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: hub.docker.com/inspurwyd/ks-plugin
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: hub.docker.com
          username: inspurwyd
          password: dckr_pat_yMRt21vCZj0PlDl14xJiqSOHeVg

      - name: Build and push sriov-network-operator
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile
    

